### ISSUE TITLE
Improve library

### ISSUE THREAD

**Issue by jubianchi** [hoaproject/Math#41]
I recently opened 3 linked PRs and they all need to be discussed correctly to be integrated altogether.

Let's sum-up:

* #38: adds new constants (original PR was #20)
* #39: allows constants/ids names to start with digits
* #40: adds support for hex/oct/bin notations

The #38 and #40 are ready, event though the #38 is kind of blocked by #39. What I think we should do:

* [ ] Close the #39 thus disallowing constants/ids names to start with digits
* [ ] Edit the #38 to remove constants starting with digit (and replace those with their plain names, e.g `2_` => `TWO_`)
* [ ] Edit #40 to use standard/generic notation for hex (`0x...`), octal (`0...`) and binary (`0b...`)

**Comment by Hywan** [comment]
Why should we disallow constant to start by a digit? I don't see why is it an issue here.

**Comment by jubianchi** [comment]
@Hywan because if we don't, we can't support generic notations for hex/bin/oct...

**Comment by Hywan** [comment]
Good. So :+1: for closing #39, :+1: to restore previous constant names, and :+1: for #40 (but its testing suite must be updated and robust).

**Comment by jubianchi** [comment]
@Hywan will do ;) Thanks!

**Comment by Hywan** [comment]
Some news?

**Comment by Hywan** [comment]
ping?
